---

- name: (main/create-database) preparing database response template
  template:
    src: "{{ role_path }}/templates/{{ oracle_dbca_response_file }}.rsp.j2"
    dest: "/tmp/{{ oracle_dbca_response_file }}.rsp"
    owner: "{{ service_user_name }}"
    mode: 0400

- name: (main/create-database) Copy our database template
  copy:
    src: "{{ role_path }}/files/{{ oracle_dbca_template_file }}.dbc"
    dest: "{{ oracle_database_oracle_home }}/assistants/dbca/templates/{{ oracle_dbca_template_file }}.dbc"
    owner: "{{ service_user_name }}"
    remote_src: true

- name: Set fact for dbca parameters database version 11g
  set_fact:
    dbca_parameters: "-silent -responseFile /tmp/{{ oracle_dbca_response_file }}.rsp"
  when: db_version is not defined or (db_version is defined and db_version == '11g')

- name: Set fact for dbca parameters database version 18c
  set_fact:
    dbca_parameters: "-silent -createDatabase -responseFile /tmp/{{ oracle_dbca_response_file }}.rsp"
  when: db_version is defined and db_version == '18c'

- name: (main/create-database) Run database configuration assistant
  shell: "{{ oracle_database_oracle_home }}/bin/dbca {{ dbca_parameters }}"
  become: true
  become_user: "{{ service_user_name }}"
  register: command_result

- name: (main/create-database) Remove dbca response file after successful database creation
  file:
    path: "/tmp/{{ oracle_dbca_response_file }}.rsp"
    state: absent
  when: command_result.stdout is search("100%")