---

# Version Number for Testing only
- name: (main) Get Environment Configuration
  git:
      repo: 'https://github.com/ministryofjustice/hmpps-env-configs'
      dest: ~/.hmpps-env-configs
      version: ALS-52

- name: Slurp Environment File to Get This Hosts Configuration
  slurp:
      src: /etc/environment
  register: environmentfile

- name: Set Current Environment
  set_fact:
    hmpps_environment: "{{ environmentfile['content'] | b64decode | regex_search('HMPPS_ENVIRONMENT=\".*\"') | regex_replace('HMPPS_ENVIRONMENT=\"(.*)\"','\\1') }}"

- name: Set Current Role
  set_fact:
    hmpps_role: "{{ environmentfile['content'] | b64decode | regex_search('HMPPS_ROLE=\".*\"') | regex_replace('HMPPS_ROLE=\"(.*)\"','\\1') }}"

- name: Get Patch Information for Primary
  include_vars: "~/.hmpps-env-configs/{{ hmpps_environment }}/ansible/group_vars/{{ hmpps_role }}_primarydb.yml"
  when: database_type == "primary"

- name: Get Patch Information for Standby (either will do as patches should be identical)
  include_vars: "~/.hmpps-env-configs/{{ hmpps_environment }}/ansible/group_vars/{{ hmpps_role }}_standbydb1.yml"
  when: database_type == "standby"

- name: Get Patch Information for All if Host Specific Configuration Not Found
  include_vars: "~/.hmpps-env-configs/{{ hmpps_environment }}/ansible/group_vars/all.yml"
