---

- name: (main/install-osbws) Copy argfile file template
  template:
    src: "{{ role_path }}/templates/osbws-argfile.j2"
    dest: "{{ oracle_osbws_installer_directory }}/osbws-argfile"
    owner: "{{ service_user_name }}"
    group: "{{ service_user_group }}"

- name: (main/install-osbws) Install osbws
  shell: ". /home/{{ service_user_name }}/.bash_profile && java -verbose -jar {{ oracle_osbws_installer_directory }}/osbws_install.jar -ARGFILE {{ oracle_osbws_installer_directory }}/osbws-argfile > /dev/null"
  become_user: "{{ service_user_name }}"
  register: install
  failed_when: install.rc !=0

# - name: debug
#   debug:
#     msg:
#       - "{{ install }}"

- name: (main/install-osbws) Create symlink libosbws.so libobk.so
  file:
    src: "{{ oracle_database_oracle_home }}/lib/libosbws.so"
    dest: "{{ oracle_database_oracle_home }}/lib/libobk.so"
    state: link
