---

- name: (main/install-osbws) Copy argfile file template
  template:
    src: "{{ role_path }}/templates/osbws-argfile.j2"
    dest: "{{ oracle_osbws_installer_directory }}/osbws-argfile"
    owner: "{{ service_user_name }}"
    group: "{{ service_user_group }}"

- name: (main/install-osbws) Install osbws
  shell: ". /home/{{ service_user_name }}/.bash_profile && java -verbose -jar {{ oracle_osbws_installer_directory }}/osbws_install.jar -ARGFILE {{ oracle_osbws_installer_directory }}/osbws-argfile" # > /dev/null"
  become_user: "{{ service_user_name }}"
  register: install
  failed_when: install.rc !=0
  # args:
  #   creates: "{{ oracle_osbws_ora_file }}"

# - name: debug
#   debug:
#     msg:
#       - "{{ install }}"

# - name: (main/install-osbws) Create symlink libosbws.so libobk.so
#   file:
#     src: "{{ oracle_database_oracle_home }}/lib/libosbws.so"
#     dest: "{{ oracle_database_oracle_home }}/lib/libobk.so"
#     owner: "{{ service_user_name }}"
#     group: "{{ service_user_group }}"
#     state: link

- name: (main/install-osbws) Extract Oracle DB backups S3 bucket name from arn
  set_fact:
    oracledb_backups_bucket_name: "{{ oracledb_backups_bucket_arn | regex_replace('^arn:aws:s3:::','') }}"

- name: (main/install-osbws) Set OSB_WS_BUCKET
  lineinfile:
    path: "{{ oracle_osbws_ora_file }}"
    regexp: '^OSB_WS_BUCKET='
    line: "OSB_WS_BUCKET={{ oracledb_backups_bucket_name }}"


- name: (main/install-osbws) Set OSB_WS_CHUNK_SIZE
  lineinfile:
    path: "{{ oracle_osbws_ora_file }}"
    regexp: '^OSB_WS_CHUNK_SIZE='
    line: "OSB_WS_CHUNK_SIZE=524288000"
