---

- name: (main/install-osbws) Copy argfile file template
  template:
    src: "{{ role_path }}/templates/osbws-argfile.j2"
    dest: "{{ oracle_osbws_installer_directory }}/osbws-argfile"
    owner: "{{ service_user_name }}"
    group: "{{ service_user_group }}"

- name: (main/install-osbws) Install osbws
  shell: "java -verbose -jar {{ oracle_osbws_installer_directory }}/osbws_install.jar -ARGFILE {{ oracle_osbws_installer_directory }}/osbws-argfile"
  become_user: "{{ service_user_name }}"
  register: install
  failed_when: install.rc !=0

- name: debug
  msg:
    - {{ install }}



  # cd ${ORACLE_HOME}/lib
  # OSBLIB=`readlink libobk.so`
  # [ -z $OSBLIB ] && ln -s libosbws.so libobk.so
  # grep -q "^OSB_WS_BUCKET=" ${ORACLE_HOME}/dbs/osbws${ORACLE_SID}.ora
  # [ $? -ne 0 ] && echo "OSB_WS_BUCKET=tf-eu-west-2-hmpps-delius-<env>-backups-s3bucket" >> ${ORACLE_HOME}/dbs/osbws${ORACLE_SID}.ora
  # grep -q "^OSB_WS_CHUNK_SIZE=" ${ORACLE_HOME}/dbs/osbws${ORACLE_SID}.ora
  # [ $? -ne 0 ] && echo "OSB_WS_CHUNK_SIZE=524288000" >> ${ORACLE_HOME}/dbs/osbws${ORACLE_SID}.ora
