---

- name: (main/install-oswbs) Copy argfile file template
  template:
    src: "{{ role_path }}/templates/osbws-argfile.j2"
    dest: "{{ oracle_osbws_installer_directory }}/osbws-argfile"
    owner: "{{ service_user_name }}"
  become_user: "{{ service_user_name }}"
