---

- name: (main) Load in our vars
  include_vars:
    file: main.yml

- block:
    - name: (main) Define our service user
      set_fact:
        service_user_name: "oracle"
  when: not service_user_name|default(false)

- name: (main) Get our instance facts
  ec2_metadata_facts:

- name: (main) Gather installation facts
  include: check-installation.yml

- name: Reconfigure our config that was set during ami build
  include: reconfigure-instance.yml

- block:
    - name: (main) Configure and startup asm
      include: configure-asm.yml

    - name: (main) Configure our flash disk groups
      include: configure-disk-groups.yml

    - name: (main) Create our check file so we don't run this again
      file:
        path: "/home/{{ service_user_name }}/.grid_installed"
        state: touch
  when: not grid_installed|default(false)
  tags: asm

- block:
    - name: (main) Configure out database
      include: create-database.yml

    - name: (main) Create our check file so we don't run this again
      file:
        path: "/home/{{ service_user_name }}/.oradb_installed"
        state: touch
  when:
    - not oradb_installed|default(false)
    - database_type != "standby"
  tags: create_db

- block:
    - name: (main) Install OPatch utility
      include: patch-oracle.yml

    - name: (main) Install PSU patch
      include: patch-psu.yml

  when:
    - not grid_installed|default(false)
    - not oradb_installed|default(false)
  tags: patch
