---

- name: (main) Load in our vars
  include_vars:
    file: main.yml
  tags: always

- block:
    - name: (main) Define our service user
      set_fact:
        service_user_name: "oracle"
  when: not service_user_name|default(false)
  tags: always

- block:
    - name: (main) Define our service user's group
      set_fact:
        service_user_group: "oinstall"
  when: not service_user_group|default(false)
  tags: always

- name: (main) Get our instance facts
  ec2_metadata_facts:
  tags: always

- name: (main) Display database type
  debug:
    var: database_type
    verbosity: 1
  tags: always

- name: (main) Gather installation facts
  include: check-installation.yml
  tags: always

- name: (main) Reconfigure our config that was set during ami build
  include: reconfigure-instance.yml
  tags: always

- block:
    - name: (main) Configure and startup asm
      include: configure-asm.yml

    - name: (main) Create our check file so we don't run this again
      file:
        path: "/home/{{ service_user_name }}/.grid_installed"
        state: touch

    - name: (main) grid installed
      set_fact:
        grid_installed: true

  when: not grid_installed|default(false)
  tags: asm

- block:
    - name: (main) Configure out database
      include: create-database.yml

    - name: (main) Create our check file so we don't run this again
      file:
        path: "/home/{{ service_user_name }}/.oradb_installed"
        state: touch

    - name: (main) oradb installed
      set_fact:
        oradb_installed: true

  when:
    - not oradb_installed|default(false)
    - grid_installed|default(false)
    - database_type != "standby"
  tags: create_db

- block:
    - name: (main) Install OPatch utility
      include: patch-oracle.yml

    - name: (main) Install PSU patch
      include: patch-psu.yml

    - name: (main) Remove our patch source archive now we have patched
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ oracle_patch_installer_directory }}/p6880880_112000_Linux-x86-64.zip"

    - name: (main) Create our check file so we don't run this again
      file:
        path: "/home/{{ service_user_name }}/.patches_applied"
        state: touch

    - name: (main) patches applied
      set_fact:
        patches_applied: true

  when:
    - grid_installed|default(false)
    - not patches_applied|default(false)
  tags: patch


- name: (main) Setup TAF Service Name
  include: set-taf-service.yml
  when:
    - grid_installed|default(false)
    - database_type != "standby"
  tags: service


#  Not Required for Local Instance
#  ===============================
# - block:
#     - name: (main) Install Oracle Secure Web Backup Service (oswbs)
#       include: install-oswbs.yml
#   when:
#     - grid_installed|bool
#     - patches_applied|bool
#   tags: oswbs

- name: (main) Display database_bootstrap_restore var
  debug:
    msg:
      - "database_type - {{database_type}}"
      - "database_bootstrap_restore - {{database_bootstrap_restore}}"
      - "backup_restored - {{backup_restored}}"
      - "grid_installed - {{grid_installed}}"
      - "oradb_installed - {{oradb_installed}}"
      - "patches_applied - {{patches_applied}}"
    verbosity: 2
  tags: always

- block:
    - name: (main) Restore Cold Backup
      include: restore-cold-backup.yml

    - name: (main) Create our check file so we don't run this again
      file:
        path: "/home/{{ service_user_name }}/.backup_restored"
        state: touch

    - name: (main) backup restored
      set_fact:
        backup_restored: true
  when:
    - database_type != "standby"
    - database_bootstrap_restore|bool
    - not backup_restored|bool
    - grid_installed|bool
    - oradb_installed|bool
    - patches_applied|bool
  tags: restore

- block:
    - name: (main) Copy huge page script
      copy:
        src: "{{ role_path }}/files/hugepages.sh"
        dest: /tmp/hugepages.sh
        mode: u+x

    - name: (main) Execute huge page script
      shell: "/tmp/hugepages.sh"
      register: hugepage_value
      failed_when: hugepage_value.rc != 0

    - name: (main) Find the value of hugepages already set
      command: /usr/bin/cat /proc/sys/vm/nr_hugepages
      register: hugepage_result
      failed_when: hugepage_result.rc != 0

    - name: (main) Configure kernel for hugepages if required
      sysctl:
        name: "vm.nr_hugepages"
        value: "{{ hugepage_value.stdout }}"
        state: present
      when: hugepage_result.stdout != hugepage_value.stdout

    - name: (main) Create our check file so we don't run this again
      file:
        path: "/home/{{ service_user_name }}/.hugepages_set"
        state: touch

    - name: (main) hugepages set
      set_fact:
        hugepages_set: true

  when:
    - database_type != "standby"
    - backup_restored|bool
    - not hugepages_set|bool
  tags: hugepages

- block:
    - name: (main) Create DB ready for HA check file standby
      file:
        path: "/home/{{ service_user_name }}/.ready_for_ha"
        state: touch
  when:
    - database_type != "primary"
    - grid_installed|bool
    - patches_applied|bool
    - not ready_for_ha|bool

- block:
    - name: (main) Create DB ready for HA check file primary
      file:
        path: "/home/{{ service_user_name }}/.ready_for_ha"
        state: touch
  when:
    - database_type != "standby"
    - grid_installed|bool
    - oradb_installed|bool
    - patches_applied|bool
    - backup_restored|bool
    - hugepages_set|bool
    - not ready_for_ha|bool

# Install all one-off patches specified for this environment
- block:
    - name: (main) Get Environment Configuration
      git:
         repo: 'https://github.com/ministryofjustice/hmpps-env-configs'
         dest: ~/.hmpps-env-configs

    - name: Slurp Environment File to Get This Hosts Configuration
      slurp:
          src: /etc/environment
      register: environmentfile

    - name: Set Current Environment
      set_fact:
        hmpps_environment: "{{ environmentfile['content'] | b64decode | regex_search('HMPPS_ENVIRONMENT=\".*\"') | regex_replace('HMPPS_ENVIRONMENT=\"(.*)\"','\\1') }}"

    - name: Set Current Role
      set_fact:
        hmpps_role: "{{ environmentfile['content'] | b64decode | regex_search('HMPPS_ROLE=\".*\"') | regex_replace('HMPPS_ROLE=\"(.*)\"','\\1') }}"

    - name: Get Patch Information for Primary
      include_vars: "~/.hmpps-env-configs/{{ hmpps_environment }}/ansible/group_vars/{{ hmpps_role }}_primarydb.yml"
      when: database_type == "primary"

    - name: Get Patch Information for Standby (either will do as patches should be identical)
      include_vars: "~/.hmpps-env-configs/{{ hmpps_environment }}/ansible/group_vars/{{ hmpps_role }}_standbydb1.yml"
      when: database_type == "standby"

    - name: Get Patch Information for All if Host Specific Configuration Not Found
      include_vars: "~/.hmpps-env-configs/{{ hmpps_environment }}/ansible/group_vars/all.yml"
      when: required_patches is not defined

    - block:
       - name: Install Patches
         include_role:
           name: oracle-db-patches
         vars:
             install_absent_patches: true
             target_host: localhost
             environment_name: "{{ hmpps_environment }}"
      become: true
      become_user: oracle
  when:
    - grid_installed|bool
    - oradb_installed|bool
    - patches_applied|bool
    - backup_restored|bool or not (database_bootstrap_restore|bool)

