---

- name: (main/patch-psu) Copy the PSU ocm response file to /tmp
  copy:
    src: "{{ role_path }}/files/ocm.rsp"
    dest: "/tmp/ocm.rsp"
    remote_src: true

- block:

    - block:

        - name: (main/patch-psu) Check status from primary database
          shell: ". ~/.bash_profile && srvctl status database -d {{ database_sid }}"
          register: database_status

        - name: (main/patch-psu) Shutdown primary database before applying patches
          shell: ". ~/.bash_profile && srvctl stop database -d {{ database_sid }} -o immediate"
          when: '"Database is running" in database_status.stdout'
          register: database_shutdown

      become: true
      become_user: "{{ service_user_name }}"  
      when:
        - oradb_installed
        - database_type != 'standby'

    - name: (main/patch-psu) Apply Composite patch 27338049
      raw: "export PATH=$PATH:/tmp;
              {{ oracle_database_oracle_home }}/OPatch/opatch napply {{ oracle_patch_installer_directory }}/27726505/27475913/27338049
                -local -silent -ocmrf /tmp/ocm.rsp -oh {{ oracle_database_oracle_home }}"
      chdir: "{{ oracle_patch_installer_directory }}/27726505/27475913/27338049"
      register: patch_result
      failed_when: "'Composite patch 27338049 successfully applied.' not in patch_result.stdout_lines"
      become: true
      become_user: "{{ service_user_name }}"
      ignore_errors: yes

    - name: (main/patch-psu) Apply OPatch 27441052/custom/server/27441052
      raw: "export PATH=$PATH:/tmp;
              {{ oracle_database_oracle_home }}/OPatch/opatch napply {{ oracle_patch_installer_directory }}/27726505/27475913/27441052/custom/server/27441052
                -local -silent -ocmrf /tmp/ocm.rsp -oh /{{ oracle_database_oracle_home }}"
      chdir: "{{ oracle_patch_installer_directory }}/27726505/27475913/27441052/custom/server/27441052"
      register: patch_result
      failed_when: "'OPatch succeeded.' not in patch_result.stdout_lines"
      become: true
      become_user: "{{ service_user_name }}"
      ignore_errors: yes

    - name: (main/patch-psu) Upgrade PSU in database
      shell: |
        . ~/.bash_profile
        srvctl start database -d {{ database_sid }}
        sqlplus '/ as sysdba' @{{ oracle_database_oracle_home }}/rdbms/admin/catbundle psu apply
        exit;
      register: sql_result
      failed_when: sql_result.rc != 0
      become: true
      become_user: "{{ service_user_name }}"
      when:
        - database_type != "standby"

    - name: (main/patch-psu) Compile invalid database objects and shutdown
      shell: |
        . ~/.bash_profile;
        sqlplus '/ as sysdba' @{{ oracle_database_oracle_home}}/rdbms/admin/utlrp
        srvctl stop database -d {{ database_sid }}
      register: sql_result
      failed_when: sql_result.rc != 0
      become: true
      become_user: "{{ service_user_name }}"
      when:
        - database_type != "standby"

    - name: (main/patch-psu) Create fuser file for OJVM upgrade
      file:
        path: "{{ oracle_database_oracle_home }}/bin/fuser"
        state: touch
        owner: "{{ service_user_name }}"
        mode: 0775

    - name: (main/patch-psu) Apply OJVM patch as oracle user
      raw: ". ~/.bash_profile;
             {{ oracle_database_oracle_home }}/OPatch/opatch apply -oh \
                {{ oracle_database_oracle_home }} {{ oracle_patch_installer_directory }}/27726505/27475598 \
                -silent -ocmrf /tmp/ocm.rsp"
      register: patch_result
      failed_when: "'OPatch succeeded.' not in patch_result.stdout_lines"
      become: true
      become_user: "{{ service_user_name }}"
      ignore_errors: yes

    - name: (main/patch-psu) Upgrade OJVM in database
      shell: 
        cmd: |
          . ~/.bash_profile
          sqlplus / as sysdba << EOF
          startup upgrade;
          @{{ oracle_database_oracle_home}}/sqlpatch/27475598/postinstall.sql;
          shutdown immediate;
          startup;
          EOF
      register: sql_result
      failed_when: sql_result.rc != 0
      become: true
      become_user: "{{ service_user_name }}"
      when:
        - database_type != "standby"

    - name: (main/patch-psu) Compile invalid database objects
      shell: ". ~/.bash_profile;
              sqlplus '/ as sysdba' @{{ oracle_database_oracle_home}}/rdbms/admin/utlrp"
      register: sql_result
      failed_when: sql_result.rc != 0
      become: true
      become_user: "{{ service_user_name }}"
      when:
        - database_type != "standby"
