---

- name: (main/patch-oracle) Backup Our OPatch Files
  archive:
    path: "{{ item }}"
    dest: "../{{ item|basename + '-' + ansible_date_time.epoch }}.tar.gz"
    remote_src: true
    remove: true
  with_items:
    - "{{ oracle_grid_oracle_home }}/OPatch"
    - "{{ oracle_database_oracle_home }}/OPatch"

- name: (main/patch-oracle) Copy opatch utility to grid home
  copy:
    remote_src: yes
    src: "{{ oracle_patch_installer_directory }}/p6880880_112000_Linux-x86-64.zip"
    dest: "{{ oracle_grid_oracle_home }}"

- name: (main/patch-oracle) Copy opatch utility to database home
  copy:
    src: "{{ oracle_patch_installer_directory }}/p6880880_112000_Linux-x86-64.zip"
    dest: "{{ oracle_database_oracle_home }}"
    remote_src: yes

- name: (main/patch-oracle) Unpack opatch utility
  unarchive:
    src: "{{ item }}/p6880880_112000_Linux-x86-64.zip"
    dest: "{{ item }}"
    owner: "{{ service_user_name }}"
    remote_src: yes
  with_items:
    - "{{ oracle_grid_oracle_home }}"
    - "{{ oracle_database_oracle_home }}"

- name: (main/patch-oracle) Remove our patch archives now we have unpacked them
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ oracle_patch_installer_directory }}/p6880880_112000_Linux-x86-64.zip"
    - "{{ oracle_grid_oracle_home }}/p6880880_112000_Linux-x86-64.zip"
    - "{{ oracle_database_oracle_home }}/p6880880_112000_Linux-x86-64.zip}}"
