---

- name: (main/restore-cold-backup) XXX
  debug:
    var: service_user_name
    verbosity: 1

- name: (main/restore-cold-backup) XXX
  debug:
    var: database_global_database_name
    verbosity: 1

- name: (main/restore-cold-backup) XXX
  debug:
    var: database_sid
    verbosity: 1

- name: (main/restore-cold-backup) XXX
  debug:
    var: database_characterset
    verbosity: 1

- name: (main/restore-cold-backup) XXX
  debug:
    var: database_type
    verbosity: 1

- name: (main/restore-cold-backup) XXX
  debug:
    var: database_bootstrap_restore
    verbosity: 1

- name: (main/restore-cold-backup) XXX
  debug:
    var: database_backup
    verbosity: 1

- name: (main/restore-cold-backup) XXX
  debug:
    var: dependencies_bucket_arn
    verbosity: 1

- name: (main/restore-cold-backup) XXX
  debug:
    msg: "{{ dependencies_bucket_arn | regex_replace('^arn:aws:s3:::','') }}"
    verbosity: 1

- name: (main/restore-cold-backup) Extract S3 bucket name from arn
  set_fact:
    src_s3_bucket_name: "{{ dependencies_bucket_arn | regex_replace('^arn:aws:s3:::','') }}"

- name: (main/restore-cold-backup) XXX
  debug:
    var: src_s3_bucket_name
    verbosity: 1

- name: (main/restore-cold-backup) Set source S3 backup path
  set_fact:
    src_s3_backup_path: "s3://{{ src_s3_bucket_name }}/{{ database_backup }}/"

- name: (main/restore-cold-backup) XXX
  debug:
    var: src_s3_backup_path
    verbosity: 1

- name: (main/restore-cold-backup) lookup ssm parameter store in nominated region
  debug:
    msg: "{{ lookup('aws_ssm', '{{ database_backup_sys_passwd }}', region=''~ region ~'' ) }}"
    verbosity: 1

- name: (main/restore-cold-backup) Set source ora db sys password
  set_fact:
    sys_passwd: "{{ lookup('aws_ssm', '{{ database_backup_sys_passwd }}', region=''~ region ~'' ) }}"
  no_log: true
